---
output:  html_document
number_sections: true
title: | 
  | FHAST Habitat Summary
header-includes:
    - \usepackage{setspace}\singlespacing
    - \usepackage{float}
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontsize: 12pt
fig_caption: yes
indent: true
---

/blandscape

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, knitr::opts_chunk$set(warning = FALSE, message = FALSE) )
library(here)

# Load Libraries and some base parameters
source(here("scripts","R","main","load_libraries.R"))
source(here("scripts","R","main","default_initialization.R"))

input_data <- read.csv(file = file.path(input_folder, fhast_config_file),
                       sep = "=",
                       row.names = 1,
                       header = FALSE) %>% 
  # Trim off white spaces form values
  rename(value = 1) %>% 
  mutate(value = str_trim(value, side = c("both")))

simulation_name = input_data["folder",]
```

```{r load_data, include=FALSE}
summary_stats = readRDS(file = here("temporary", "R", "summary_stats_table.rds")) 

fish_summary_stats = readRDS(file = here("temporary", "R", "summary_fish_stats_table.rds"))

cover_scatter_plot = readRDS(file = here("temporary", "R", "cover_scatter_plot.rds"))

cover_facet_map = readRDS(file = here("temporary", "R", "cover_facet_map.rds"))

pred_map = readRDS(file = here("temporary", "R", "predator_map.rds"))

cutoff_map = readRDS(file = here("temporary", "R", "cutoff_map.rds"))

heat_map_plot = readRDS(file = here("temporary", "R", "depth_velocity_heatmap.rds"))

fish_met_plot = readRDS(file = here("temporary", "R", "metabolic_map.rds"))

fish_pred_plot = readRDS(file = here("temporary", "R", "predation_map.rds"))

```

### Simulation name: `r simulation_name`
***
## Tabular Outputs 

```{r print_summary_stats, echo = FALSE}
kable(summary_stats, caption = "The habitat summary statistics.")
```

```{r print_fish_summary_stats, echo = FALSE}
kable(fish_summary_stats, caption = "The fish summary statistics.")
```

\newpage
## Figures Outputs

```{r print_cover_figure, echo = FALSE, fig.align="center", fig.cap = "Cover shallower than cutoff."}
print(cover_scatter_plot)
```

```{r print_pred_figure, echo = FALSE, fig.align="center", fig.cap = "The predation risk map."}
print(pred_map)
```

```{r print_facet_map, echo = FALSE, fig.align="center", fig.cap = "Porportion of cover divided out by velocity and depth cutoffs.."}
print(cover_facet_map)
```

```{r print_heatmap_figure, echo = FALSE, fig.align="center", fig.cap = "The depth and velocity heatmap risk map."}
print(heat_map_plot)
```

```{r print_fish_met_figure, echo = FALSE, fig.height = 30,  fig.align="center", fig.cap = "The metabolic rate of the fish."}
print(fish_met_plot, height = 60)
```

```{r print_fish_pred_figure, echo = FALSE, fig.height = 30,  fig.align="center", fig.cap = "The predation rate of the fish."}
print(fish_pred_plot, height = 60)
```

\newpage
## Appendix
### Run inputs
The main input file:
```{r, echo=FALSE}
cat(readLines(file.path(input_folder, fhast_config_file)), sep = '\n')
```
---

The daily input file:
```{r, echo=FALSE, }
cat(readLines(file.path(input_folder, input_data["folder",], "daily", input_data["daily file",])), sep = '\n')
```
---

The fish population file:
```{r, echo=FALSE, }
cat(readLines(file.path(input_folder, input_data["folder",],
                        "fish", input_data["fish population file",])), sep = '\n')
```
---

The fish parameter file:

---
```{r, echo=FALSE, }
cat(readLines(file.path(input_folder, input_data["folder",],
                        "fish", input_data["fish parameters file",])), sep = '\n')
```
---

The grid resolution file:
```{r, echo=FALSE, }
cat(readLines(file.path(input_folder, input_data["folder",],
                        "grid", input_data["grid resolution file",])), sep = '\n')
```
---

The habitat parameter file:
```{r, echo=FALSE, }
cat(readLines(file.path(input_folder, input_data["folder",],
                        "habitat", input_data["habitat parameters file",])), sep = '\n')
```
---

The predator input file (not yet set indepidently):
```{r, echo=FALSE, }
print("to be set")
```
---